### ISSUE TITLE
运行后访问9501返回{"err_code":10000,"err_msg":"system busy"}

### ISSUE THREAD

**Issue by neilqin** [parker714/yii2-s#1]
{"err_code":10000,"err_msg":"system busy"}

**Comment by parker714** [comment]
这里对异常组件进行了重写，具体代码在components/ErrorHandler.php

本地开发，设置bin/swHttp.php的 YII_DEBUG 为 true 即可
 
就会有调试信息
{
    "err_code": 10000,
    "err_msg": "system busy",
    "debug": {
        "err_code": 0,
        "err_mse": "Page not found.",
        "err_file": "/Users/pb/Work/swoole-yii2/vendor/yiisoft/yii2/web/Request.php",
        "err_line": 284
    }
}
